name: Check Commit Messages

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check Commit Messages
      run: |
        git fetch origin ${{ github.event.pull_request.head.ref }}
        git checkout ${{ github.event.pull_request.head.ref }}
        
        commit_range="${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
        
        commit_messages=$(git log --pretty=format:%s $commit_range)
        
        for commit_message in $commit_messages; do
          if [ -z "$commit_message" ]; then
            echo "Commit message is empty"
            new_commit_message="Additional commit message"
            echo "$new_commit_message" > commit_message.txt
            git cherry-pick --no-commit $commit_range
            git commit --amend -F commit_message.txt --no-edit
            git show
          else
            echo "Commit message is not empty"
          fi
        done
